# Generated by Django 5.1 on 2024-09-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("matricula", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("endereco", models.CharField(max_length=255)),
                (
                    "curso",
                    models.CharField(
                        choices=[
                            ("INFORMATICA", "Informática"),
                            ("ALIMENTOS", "Alimentos"),
                            ("APICULTURA", "APICULTURA"),
                        ],
                        max_length=255,
                    ),
                ),
            ],
        ),
    ]
